[package]
name = "default-target"
version = "0.1.0"
authors = ["James Mishra <james.mishra@neocrym.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
