name: publish-rust

defaults:
  run:
    shell: bash

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish-rust:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Log into crates.io
      run: cargo login ${{ secrets.CRATES_IO_TOKEN }}

    - name: Publish to crates.io
      run: cargo publish
